services:
  main:
    container_name: cats-main
    build:
      context: ./
      dockerfile: dockerfiles/cats-main.dockerfile
    volumes:
      # - ./cgi-bin/cats-problem:/home/cats-main/cgi-bin/cats-problem
      # - ./cgi-bin/CATS:/home/cats-main/cgi-bin/CATS
      - type: bind
        source: ./dockerfiles/main/Config.pm
        target: /app/cgi-bin/cats-problem/CATS/Config.pm
      - ./var/log/apache2:/var/log/apache2
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - postgres
  
  postgres:
    container_name: cats-postgres
    build:
      context: ./
      dockerfile: dockerfiles/postgres.dockerfile
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    ports:
      - "5432:5432"
    volumes:
      - v-postgres:/var/lib/postgresql/data
      - ./var/log/postgresql:/var/log/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER} -d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  judge:
    container_name: cats-judge
    build:
      context: ./cats-judge
    volumes:
      - type: bind
        source: ./cats-judge/dockerfiles/judge/Config.pm
        target: /app/lib/cats-problem/CATS/Config.pm
      - type: bind
        source: ./cats-judge/dockerfiles/judge/local.xml
        target: /app/config/local.xml
    depends_on:
      - postgres
    restart: always

volumes:
  v-postgres:
  v-problems:
  v-media:
