services:
  main:
    container_name: cats-main
    build:
      context: ./
      dockerfile: dockerfiles/cats-main.dockerfile
    volumes:
      - ./cgi-bin/cats-problem:/home/cats-main/cgi-bin/cats-problem
      - ./logs/apache2:/var/log/apache2
      - ./cgi-bin/CATS:/home/cats-main/cgi-bin/CATS
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - postgres
  
  postgres:
    container_name: cats-postgres
    build:
      context: ./
      dockerfile: dockerfiles/postgres.dockerfile
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-db_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-db_pass}"
      POSTGRES_DB: "${POSTGRES_DB:-db_name}"
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - v-postgres:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-db_user} -d", "${POSTGRES_DB:-db_name}", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  judge:
    container_name: cats-judge
    build:
      context: ./cats-judge
    volumes:
      - ./cats-judge/dockerfiles/Config.pm:/app/lib/cats-problem/CATS/Config.pm
      - ./cats-judge/dockerfiles/local.xml:/app/config/local.xml
    depends_on:
      - postgres
    restart: always

volumes:
  v-postgres:
  v-problems:
  v-media:
