services:
  main:
    container_name: cats-main
    env-file: .env
    build:
      context: ./
      dockerfile: dockerfiles/cats-main.dockerfile
    volumes:
      - type: bind
        source: ./dockerfiles/main/Config.pm
        target: /app/cgi-bin/cats-problem/CATS/Config.pm
      - v-main-apache-log:/var/log/apache2
    ports:
      - "${CATS_MAIN_HOST_PORT}:80"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: cats-postgres
    build:
      context: ./
      dockerfile: dockerfiles/postgres.dockerfile
    env-file: .env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - v-postgres-data:/var/lib/postgresql/17/main
      - v-postgres-conf:/etc/postgresql/17/main
      - v-postgres-log:/var/log/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  judge:
    container_name: cats-judge
    privileged: true
    image: registry.mesenev.ru/mesenev/cats-judge:latest
    env-file: .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: always

volumes:
  v-main-apache-log:
  v-postgres-data:
  v-postgres-conf:
  v-postgres-log:
  v-problems:
  v-media:
