name: Cats CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy Cats
    runs-on: [ self-hosted, linux, x64 ]
    environment: production
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup environment
      run: |
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_HOST_PORT=${{ secrets.POSTGRES_HOST_PORT }}" >> .env
        echo "CATS_MAIN_HOST_PORT=${{ secrets.CATS_MAIN_HOST_PORT }}" >> .env
      shell: bash

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Docker Compose build
      run: make build

    - name: Docker Compose up
      run: make up
